#!/bin/bash

#$ -S /bin/bash             # use bash shell
#$ -V                       # inherit the submission environment 
#$ -cwd                     # start job in submission directory

#$ -m abe                   # email on abort, begin, and end
#$ -M mansbac2@illinois.edu      # email address
#$ -o umbrellaXXX.log
#$ -N CCCumbrellaXXX               # job name
#$ -j y
#$ -q all.q                 # queue name
#$ -pe orte 1             # parallel environment & # cores
##$ -l h_rt=00:10:00        # run time (hh:mm:ss)
##$ -l hostname=compute-0-20

echo " "
echo "-------------------"
echo "This is a $ENVIRONMENT job"
echo "This job was submitted to the queue: $QUEUE"
echo "The job's id is: $JOB_ID"
echo "The job's name is: $JOB_NAME"
echo "The job's home dir is: $SGE_O_HOME"
echo "The job's working dir is: $SGE_O_WORKDIR"
echo "The host node of this job is: $SGE_O_HOST"
echo "The master node of this job is: $HOSTNAME"
echo "The number of cores used by this job: $NSLOTS"
echo "This job was submitted by: $SGE_O_LOGNAME"
echo "-------------------"
echo Running on host `hostname`
echo Time is `date`
echo "-------------------"
echo " "

cd $SGE_O_WORKDIR
RUNDIR=/share/scratch/ramansbach/coarsegraining/martini-assembly/pmf2ndStructCheck/CCC/5_umbrella
cd $RUNDIR

NOMP=$NSLOTS
if [ `expr $NMPI \* $NOMP` -ne $NSLOTS ] ; then
    echo "ERROR: NMPI*NOMP != NSLOTS"
    exit -1
fi
mkdir runXXX
cd runXXX
cp ../table* .
cp ../*.itp .
cp ../CG_DFAG.top .
cp ../Protein* .
cp ../index.ndx .
cp ../residuetypes.dat .
cp ../npt_umbrella.mdp .
cp ../umbrella.mdp .
mv ../confXXX.gro .


/share/apps/gromacs467/bin/grompp -v -f npt_umbrella.mdp -c confXXX.gro -p CG_DFAG.top -n index.ndx -o nptXXX.tpr 
/share/apps/gromacs467/bin/mdrun -pin off -nt 1 -nb cpu -v -s nptXXX.tpr -o nptXXX.trr -c nptXXX.gro -g nptXXX.log -e nptXXX.edr -x nptXXX.xtc -cpo nptXXX.cpt

/share/apps/gromacs467/bin/grompp -v -f umbrella.mdp -po umbrella_grompp.mdp -c nptXXX.gro -p CG_DFAG.top -o umbrellaXXX.tpr -n index.ndx -t nptXXX.cpt
/share/apps/gromacs467/bin/mdrun -pin off -nt 1 -nb cpu -v -s umbrellaXXX.tpr -o umbrellaXXX.trr -c umbrellaXXX.gro -g umbrellaXXX.log -e umbrellaXXX.edr -x umbrellaXXX.xtc -cpo umbrellaXXX.cpt -pf pullf-umbrellaXXX.xvg -px pullx-umbrellaXXX.xvg 




cd $SGE_O_WORKDIR
echo " "
echo "This job is DONE!"
echo " "

exit 0

